#pragma once
#include <Arduino.h>

// Automatically generated by train_tinyml.py
static const int TINYML_N_CLASSES = 3;
static const int TINYML_N_FEATURES = 2;

static const int TINYML_CLASSES[3] = { 0, 1, 2 };

static const float TINYML_MEAN[2] = { 32.795615f, 56.733714f };
static const float TINYML_SCALE[2] = { 1.292996f, 7.450685f };

static const float TINYML_WEIGHTS[3][2] = {
  { -9.794974f, 5.773031f },
  { 2.509532f, -1.959574f },
  { 7.285443f, -3.813457f }
};

static const float TINYML_BIASES[3] = { -21.070522f, 17.775744f, 3.294778f };

static inline int tinyml_predict(float temp, float hum) {
  // Chuẩn hóa giống trên PC
  float x0 = (temp - TINYML_MEAN[0]) / TINYML_SCALE[0];
  float x1 = (hum  - TINYML_MEAN[1]) / TINYML_SCALE[1];
  float best_logit = -1e9f;
  int best_idx = 0;
  for (int i = 0; i < TINYML_N_CLASSES; ++i) {
    float z = TINYML_WEIGHTS[i][0] * x0 + TINYML_WEIGHTS[i][1] * x1 + TINYML_BIASES[i];
    if (z > best_logit) { best_logit = z; best_idx = i; }
  }
  // Trả về nhãn gốc (0,1,2,...)
  return TINYML_CLASSES[best_idx];
}
